# Generated by Django 2.2.5 on 2019-10-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Item',
            new_name='item',
        ),
    ]
