# Generated by Django 2.2.5 on 2019-10-10 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('buying_price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('value_added_tax', models.IntegerField(default=16)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
