# Generated by Django 2.2.5 on 2019-10-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20191010_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
